### ISSUE TITLE
CuDNN library mismatch

### ISSUE THREAD

**Issue by alperyilmaz** [rocker-org/rocker-versioned2#235]
I pulled `rocker/ml:4.1.1-cuda11.1` and installed Tensorflow within, `install_keras(tensorflow="gpu")`. Then I generated Keras model and compiled it. During fitting I got the following error:
```
2021-09-08 12:25:02.448364: E tensorflow/stream_executor/cuda/cuda_dnn.cc:362] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2021-09-08 12:25:02.453002: E tensorflow/stream_executor/cuda/cuda_dnn.cc:362] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Error in py_call_impl(callable, dots$args, dots$keywords) :
  UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	[[node sequential_1/conv2d_1/Conv2D (defined at /keras/engine/training.py:1184) ]] [Op:__inference_train_function_948]
```
As far as I can tell, the [Dockerfile for this image](https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/cuda11_4.1.1.Dockerfile) is based on `nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04` image. Isn't this supposed to be installed with matching versions of libraries? How can I troubleshoot or solve this problem?

I might have picked the wrong image, since there are so many choices. In that case, can you please point me to a working image in which Keras/TF works with R?
thanks

**Comment by eitsupi** [comment]
Hello. I'm not familiar with cuda, but I traced where the version of cudnn `8.0.5.39-1+cuda11.1` is specified and found it in the Dockerfile of the base image.
https://gitlab.com/nvidia/container-images/cuda/-/blob/4add3647cdca81594f3c545211391fdd3d9b4900/dist/11.1.1/ubuntu20.04/runtime/cudnn8/Dockerfile#L6

I searched for the error message and found the following issue, which suggests that the version of tensorflow may be too new (tensorflow-2.5.0).
https://github.com/tensorflow/text/issues/554

**Comment by cboettig** [comment]
@alperyilmaz thanks for the report, and thanks @eitsupi for the analysis here.  

@RobJY is looking into configuration and testing for GPU across a variety of tensorflow versions, still a work in progress, see https://github.com/rocker-org/rocker-versioned2/pull/210/files.  @RobJY can you take a look at this issue as well?  Did you come across this in your tests on Tensorflow 2.5 / 2.6?

@alperyilmaz hopefully in the future we'll have this better nailed down.  Tensorflow seems particularly picky about library version matches when using GPU.  (In my experience, pytorch is less picky about this, and of course the cpu-only versions of either one are not impacted by this, but that's not much help!)  Meanwhile, can you test with an earlier version of tensorflow (say, 2.2?) and see if that works?

**Comment by alperyilmaz** [comment]
hi, thanks @eitsupi for your analysis.. @cboettig I'll be more than happy to test another version but don't know which image is TF 2.2

by the way, I pulled `rocker/ml:4.1.1-cuda10.1` image, installed "tensorflow-gpu" and then during training I got the following error:
```
2021-09-08 16:10:27.952860: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/venv/reticulate/lib:/opt/venv/reticulate/lib:/opt/venv/reticulate/lib:/usr/local/lib:/usr/lib:/opt/venv/reticulate/lib:/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64/libnvblas.so:
```
As far as I can tell, the base image is from nvidia, so it's puzzling how come there are so many incompatibility issues within those images. Screening through versions for GPU would help weed out incompatible images which should have been eliminated by nvidia in the first place. I had bad luck with Python images (base tensorflow images) as well. I need to pull and test 3-4 images and find out which one works. 
I agree your comments about PyTorch, it's wasting less time of many people when compared to Tensorflow. Sorry for long comment..

**Comment by RobJY** [comment]
I haven't seen this specific error, but depending on how I installed tensorflow I did have to install other packages to make it work.  I had a version where I needed to manually install cudnn.  You can see this in my commit history of the PR mentioned above.

To install tensorflow I'm currently using:
```
install.packages("tensorflow")
tensorflow::install_tensorflow(version="${ver}-gpu", extra_packages="tensorflow-probability==0.7.0")
```
I chose this because it was recommended on [this dockerhub page](https://hub.docker.com/r/rocker/cuda).
This has worked for me with ${ver} set to 2.2, 2.5 and 2.6.  My test of a working install has been that tests/ml/nvblas.R runs successfully.

**Comment by alperyilmaz** [comment]
Hi @RobJY , thanks for your help. I tried the following TF and Docker image combinations in which I installed tensorflow using your instructions.

| TF	| Docker image	| Error	| Notes |
|----|-----|-----|------|
| 2.2-gpu	| rocker/ml:4.1.1-cuda10.1	| Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR	| |
| 2.2-gpu	| rocker/ml:4.1.1-cuda11.1	| Could not load dynamic library 'libcudart.so.10.1’, 'libcublas.so.10’, 'libcusolver.so.10’, 'libcusparse.so.10’, ‘'libcudnn.so.7’	| but successfully loaded libcuda.so.1, libcufft.so.10, libcurand.so.10,|
| 2.3-gpu	| rocker/ml:4.1.1-cuda11.1	| ditto	| ditto| 
| 2.4-gpu	| rocker/ml:4.1.1-cuda11.1	| Could not load dynamic library ‘libcusolver.so.10’	| but successfully loaded libcudart.so.11.0, libcuda.so.1, libcudart.so.11.0, libcublas.so.11, libcublasLt.so.11, libcufft.so.10, libcurand.so.10, libcusparse.so.11, libcudnn.so.8 |
| 2.5-gpu	| rocker/ml:4.1.1-cuda11.1	| Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version.| |	

Is there any particular combination you suggest me testing?

**Comment by cboettig** [comment]
@alperyilmaz 

If I use cuda10.1 image,

```
docker run --pull --rm -ti --gpus all rocker/ml:4.1.1-cuda10.1 bash
```

and tensorflow 2.2:

```
pip install tensorflow-gpu==2.2
```
and launch python, it tells me tensorflow can find all the libraries it needs:

```python
import tensorflow as tf
tf.config.list_physical_devices('GPU') 
```

Are you sure you  ran docker with gpu mode in your 10.1 test?

With tensorflow 2.4 on cuda-11.1, I get the same error as you show.  But with tensorflow 2.5 and 2.6 on the cuda-11.1 rocker image (`rocker/ml-4.1.1-cuda11.1`) the above also works fine, reporting a working GPU device. (Maybe it would still error on running your code, please provide a minimal reproducible example we can test?)

**Comment by alperyilmaz** [comment]
hi @cboettig , sorry for bothering you so much. For R, I get errors at two different stages. Some of the errors are at model definition, as soon as I run `keras_model_sequential()`. In some cases I can pass that stage and get error at `model %>% fit()` stage. IMHO, just confirming TF version or checking if GPU is detected will lead to incomplete test. Again, IMHO, the test should complete all steps. 

I'll test your suggested combinations. I can provide a MWE but even MNIST or CIFAR10 should suffice, still I'll provide code for testing.

thanks for your help again.

**Comment by alperyilmaz** [comment]
hi, I tested 2.2-gpu with two different cuda versions and tested 2.5-gpu with cuda11, here are the results:

| TF ver | Image | Stage1: model_generate | Stage2: model fit |
|-------|---------|----------------------------|--------------------|
| 2.2-gpu | rocker/ml:4.1.1-cuda10.1 | OK | Error: tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR | 
| 2.2-gpu | rocker/ml:4.1.1-cuda11.1 | Could not load dynamic library 'libcudart.so.10.1’, 'libcublas.so.10’, 'libcusolver.so.10’, 'libcusparse.so.10’, ‘'libcudnn.so.7’ | uses CPU | 
| 2.5-gpu  | rocker/ml:4.1.1-cuda11.1 | OK | Error: tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.|

Here's how I start Docker image and install TF
```
$ docker run --pull --rm -ti --gpus all rocker/ml:4.1.1-cuda10.1 bash  # or cuda11.1
# R
> install.packages("tensorflow")
> tensorflow::install_tensorflow(version = "2.2-gpu")  # or 2.5-gpu
> install.packages("keras")
```

And here's an example R script to test
```R
 library(keras)
 library(magrittr)
 x_train <- array(runif(1000*2*100),dim=c(1000,2,100,1))
 x_val <- array(runif(100*2*100),dim=c(100,2,100,1))
 y_train <- sample(c(0,1),1000, replace = T)
 y_val <- sample(c(0,1),100, replace = T)

model <- keras_model_sequential() %>%
  layer_conv_2d(filters = 32, kernel_size = c(2,5), activation = "relu", input_shape = c(2,100,1), padding = "same") %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>%
  layer_conv_2d(filters = 64, kernel_size = c(2,5), activation = "relu", padding = "same") %>%
  layer_flatten() %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")

  model %>% compile(
    optimizer = "rmsprop",
    loss = "binary_crossentropy",
    metrics = c("accuracy")
  )
  history <- model %>% fit(
    x_train,
    y_train,
    epochs = 5,
    batch_size = 128,
    validation_data = list(x_val, y_val)
  )
```

**Comment by alperyilmaz** [comment]
Since TF 2.4-gpu gave the minimum error, one missing library. I tested 2.4.0, 2.4.1, 2.4.2 separately and they all gave the same error.

The error message is `Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/venv/reticulate/lib:/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server:/usr/local/nvidia/lib:/usr/local/nvidia/lib64`

When I search for `libcusolver.so` I found out that the Docker image had `libcusolver-11-1` and `libcusolver-dev-11-1` packages installed, which provide `/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcusolver.so` file.

I tried making a symlink with `ln -s /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcusolver.so.11 /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcusolver.so.10` and it didn't work.

Strange thing is, during loading libraries, there's message saying "Successfully opened dynamic library libcurand.so.10" and that file is also in the same directory with "libcusolver.so". So, this shouldn't be LD_LIBRARY_PATH issue. However the error message indicates that it checks "LD_LIBRARY_PATH: /opt/venv/reticulate/lib:/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server:/usr/local/nvidia/lib:/usr/local/nvidia/lib64" folders  which lacks "/usr/local/cuda-11.1/targets/x86_64-linux/lib/" so, in terminal I added that folder to LD_LIBRARY_PATH via `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.1/targets/x86_64-linux/lib/` then I tried running the Rscript. This time it loaded the library, yay :partying_face: .. 

but during model fit I got the familiar error: `Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR` so back to square one :cry:

**Comment by eitsupi** [comment]
@alperyilmaz Is there any possibility that this is affected by the use of venv etc?
https://github.com/tensorflow/tensorflow/issues/43947#issuecomment-727655093

**Comment by alperyilmaz** [comment]
@eitsupi might be.. 
I think I passed the libcusolver part by including its path but then later failed for some other reason, hitting the `CUDNN_STATUS_INTERNAL_ERROR` barrier.. 
the paths, environments  should have been taken care of during Cuda or TF installation in base Nvidia image, by Nvidia, I guess.. TF installation looks like a black hole.. sucking time and effort.. :black_circle:

**Comment by cboettig** [comment]
@alperyilmaz thanks for all the follow-up here, much appreciated.

Yeah, last I looked (may 2+ yrs ago) building TF from source looked epic, definitely don't advise that route.

It's curious why the binaries from PyPi seem to be trying to link against a mix of cuda 11.1 and cuda 10 libs.

The CuDNN 8.0.5 vs 8.1 thing is a little more reasonable; and it's documented clearly in https://www.tensorflow.org/install/gpu.  Not clear why the official NVIDIA image is pinned at 8.05.  The official tensorflow Dockerfiles build from the official NVIDIA dockerfiles too, but I think they choose a more base NVIDIA image and then add CuDNN etc, e.g. https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile#L31

We should probably adopt this in our 11.1 build scripts.  

@RobJY want to take a stab at this?  It's probably worth changing this before getting much farther in the testing.  Also as @alperyilmaz notes we want to be sure to test actual runs and not just GPU status.  Actually we had some old example code we had for this  https://github.com/rocker-org/ml/blob/master/examples/examples.R (also has tests for greta, which I think is still on tensorflow 1.x, and xgboost, which iirc required some heavy additional config and we can maybe ignore for now), but also see Alper's example above.

**Comment by cboettig** [comment]
FWIW, I think the simplest work-around right now is to use the CUDA 11.1 images with tensorflow >= 2.5 and merely upgrade libcuddn8, e.g.

```bash
apt-get update && apt-get install libcuddn8
```

Currently this gets 8.2 but that seems to work for the MRE you give above (thanks!).  You could pin to the 8.1 version mentioned in the tensorflow dockerfile linked above, that seems to work too.

**Comment by RobJY** [comment]
I'll start by adding examples.R to my test script and see if that runs into any problems if that sounds good.

**Comment by RobJY** [comment]
I get the error:
```
 tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/venv/reticulate/lib:/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64/libnvblas.so:
```
when I try to run the tensorflow section of the example.R script, so this is a good test.  I'll add it to my test script and try it on the different versions of driver, toolkit and tensorflow.

**Comment by alperyilmaz** [comment]
@cboettig thanks for the tip, now it works. So, the Dockerfile below works for me:
```Dockerfile
FROM rocker/ml:4.1.1-cuda11.1

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

RUN apt update && apt install -y --allow-change-held-packages libcudnn8 && rm -rf /var/lib/apt/lists/*

RUN Rscript -e 'install.packages("tensorflow"); tensorflow::install_tensorflow(version = "2.6-gpu"); install.packages("keras")'
```

The image is 17GB large but "minimal image size" is minimal concern for now. thanks for your time and support and patience.

**Comment by alperyilmaz** [comment]
BTW, I forgot to mention, I'm getting some warnings about ptxas binary, but I'm assuming that it's not too important:

```
I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
W tensorflow/stream_executor/gpu/asm_compiler.cc:77] Couldn't get ptxas version string: Internal: Couldn't invoke ptxas --version
I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Failed to launch ptxas
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
```

**Comment by cboettig** [comment]
@alperyilmaz excellent! thanks for confirming.  yup, I see the ptax messages too, seems to be a known bug.
https://github.com/tensorflow/tensorflow/issues/33375#issuecomment-911852358, but doesn't look important to me either.

It does look like it might go away if we symlink `/usr/local/nvidia/bin`  (need to double-check if that's the right path) to  `/usr/local/cuda/bin` but haven't tried.

**Comment by thusinh1969** [comment]
> @alperyilmaz excellent! thanks for confirming. yup, I see the ptax messages too, seems to be a known bug. [tensorflow/tensorflow#33375 (comment)](https://github.com/tensorflow/tensorflow/issues/33375#issuecomment-911852358), but doesn't look important to me either.
> 
> It does look like it might go away if we symlink `/usr/local/nvidia/bin` (need to double-check if that's the right path) to `/usr/local/cuda/bin` but haven't tried.

No it DOES NOT go away.
